version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: oracle-db-gs
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./oracle_scripts:/container-entrypoint-initdb.d
    healthcheck:
      test: >
        bash -c "echo 'select 1 from v\$instance where status = ''OPEN'';' \
        | sqlplus system/oracle@//localhost:1521/XE"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 80s

  global-solution-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: global-solution-app-gs
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:oracle:thin:@oracle-db:1521/XE
      - DB_USER=system
      - DB_PASSWORD=oracle
    depends_on:
      oracle-db:
        condition: service_healthy
    networks:
      - gs_network

volumes:
  oracle_data:

networks:
  gs_network:
    driver: bridge
