CREATE TABLE AREA_MONITORADA (
  ID_AREA          NUMBER(10)       CONSTRAINT PK_AREA_MONITORADA PRIMARY KEY,
  NOME_AREA        VARCHAR2(100)    CONSTRAINT NN_AREA_NOME NOT NULL,
  LATITUDE_CENTRO  NUMBER(9,6)      CONSTRAINT NN_AREA_LAT NOT NULL,
  LONGITUDE_CENTRO NUMBER(9,6)      CONSTRAINT NN_AREA_LON NOT NULL,
  RAIO_KM          NUMBER(5,2)      CONSTRAINT NN_AREA_RAIO NOT NULL
                              CONSTRAINT CK_AREA_RAIO CHECK(RAIO_KM > 0)
);

CREATE TABLE SENSOR (
  ID_SENSOR    NUMBER(10)     CONSTRAINT PK_SENSOR PRIMARY KEY,
  ID_AREA      NUMBER(10)     CONSTRAINT NN_SENSOR_AREA NOT NULL,
  TIPO_SENSOR  VARCHAR2(50)   CONSTRAINT NN_SENSOR_TIPO NOT NULL,
  LATITUDE     NUMBER(9,6)    CONSTRAINT NN_SENSOR_LAT NOT NULL
                              CONSTRAINT CK_SENSOR_LAT CHECK(LATITUDE BETWEEN -90 AND 90),
  LONGITUDE    NUMBER(9,6)    CONSTRAINT NN_SENSOR_LON NOT NULL
                              CONSTRAINT CK_SENSOR_LON CHECK(LONGITUDE BETWEEN -180 AND 180),
  STATUS       VARCHAR2(20)   CONSTRAINT NN_SENSOR_STATUS NOT NULL,
  CONSTRAINT FK_SENSOR_AREA FOREIGN KEY (ID_AREA)
    REFERENCES AREA_MONITORADA(ID_AREA)
);

CREATE TABLE LEITURA_SENSOR (
  ID_LEITURA       NUMBER(12)   CONSTRAINT PK_LEITURA_SENSOR PRIMARY KEY,
  ID_SENSOR        NUMBER(10)   CONSTRAINT NN_LEITURA_SENSOR NOT NULL,
  TIMESTAMP_LEITURA TIMESTAMP   CONSTRAINT NN_LEITURA_TS NOT NULL,
  TIPO_MEDICAO     VARCHAR2(50) CONSTRAINT NN_LEITURA_TIPO NOT NULL,
  VALOR_MEDICAO    NUMBER(7,2)  CONSTRAINT NN_LEITURA_VAL NOT NULL
                              CONSTRAINT CK_LEITURA_VAL CHECK (VALOR_MEDICAO >= 0),
  CONSTRAINT FK_LEITURA_SENSOR FOREIGN KEY (ID_SENSOR)
    REFERENCES SENSOR(ID_SENSOR)
);

CREATE TABLE EQUIPE_RESPOSTA (
  ID_EQUIPE     NUMBER(10)     CONSTRAINT PK_EQUIPE PRIMARY KEY,
  NOME_EQUIPE   VARCHAR2(100)  CONSTRAINT NN_EQUIPE_NOME NOT NULL,
  BASE_OPERACAO VARCHAR2(100)  CONSTRAINT NN_EQUIPE_BASE NOT NULL
);

CREATE TABLE ALERTA_INCENDIO (
  ID_ALERTA           NUMBER(10)    CONSTRAINT PK_ALERTA PRIMARY KEY,
  ID_LEITURA_GATILHO  NUMBER(12)    CONSTRAINT NN_ALERTA_LEITURA NOT NULL,
  ID_EQUIPE_DESIGNADA NUMBER(10),
  NIVEL_SEVERIDADE    VARCHAR2(20)  CONSTRAINT NN_ALERTA_NIVEL NOT NULL,
  STATUS_ALERTA       VARCHAR2(20)  CONSTRAINT NN_ALERTA_STATUS NOT NULL,
  CONSTRAINT FK_ALERTA_LEITURA FOREIGN KEY (ID_LEITURA_GATILHO)
    REFERENCES LEITURA_SENSOR(ID_LEITURA),
  CONSTRAINT FK_ALERTA_EQUIPE FOREIGN KEY (ID_EQUIPE_DESIGNADA)
    REFERENCES EQUIPE_RESPOSTA(ID_EQUIPE)
);
